GET https://my-json-server.typicode.com/z0r0v/xhr/masters HTTP/1.1;
###
GET https://my-json-server.typicode.com/z0r0v/xhr/masters/2 HTTP/1.1;
###
POST https://my-json-server.typicode.com/z0r0v/xhr/masters/ HTTP/1.1

content-type: application/json

{
  "id": 3,
  "login": "c",
  "pasword": "621",
  "firstName": "Anton",
  "LastName": "Vasilevsli",
  "dateEmployment": "2016-07-18T11:24:00.000Z",
  "categoryHired": 3,
}





